/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IconHvif {
        /**
          * The last name
         */
        "data": any;
        /**
          * The name
         */
        "name": string;
        /**
          * The last name
         */
        "size": number;
    }
}
declare global {
    interface HTMLIconHvifElement extends Components.IconHvif, HTMLStencilElement {
    }
    var HTMLIconHvifElement: {
        prototype: HTMLIconHvifElement;
        new (): HTMLIconHvifElement;
    };
    interface HTMLElementTagNameMap {
        "icon-hvif": HTMLIconHvifElement;
    }
}
declare namespace LocalJSX {
    interface IconHvif {
        /**
          * The last name
         */
        "data"?: any;
        /**
          * The name
         */
        "name"?: string;
        /**
          * The last name
         */
        "size"?: number;
    }
    interface IntrinsicElements {
        "icon-hvif": IconHvif;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "icon-hvif": LocalJSX.IconHvif & JSXBase.HTMLAttributes<HTMLIconHvifElement>;
        }
    }
}
